/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    ChartControls: typeof import('./src/components/ChartControls.vue')['default']
    DashboardPage: typeof import('./src/components/DashboardPage.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    HeatmapChart: typeof import('./src/components/HeatmapChart.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RadarChart: typeof import('./src/components/RadarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolCoverageGap: typeof import('./src/components/ToolCoverageGap.vue')['default']
  }
}
